using System;

namespace DatingApp.API.Models
{
    public class Photo
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public DateTime DateAdded { get; set; }
        public bool IsMain { get; set; }

        public User User { get; set; }
        public int UserId { get; set; }

        public string PublicId { get; set; } // This will be used to store pulic id generated by cloudinary when any photo is uploaded.
        
    }
}